apiVersion: v1
kind: PersistentVolume
metadata:
  name: tony-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/logs/commercialorder"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tony-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tony-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tony-springboot
  template:
    metadata:
      labels:
        app: tony-springboot
    spec:
      containers:
        - name: tony-springboot
          image: shinnlove/springboot:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /commercialorder
              name: tony-volume-claim
      volumes:
        - name: tony-volume-claim
          hostPath:
            path: "/data/logs/commercialorder"
---
apiVersion: v1
kind: Service
metadata:
  name: tony-service
spec:
  type: NodePort
  selector:
    app: tony-springboot
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30010

